In [1]:
# 多项式回归
import math
import numpy as np
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
# 生成数据集
max_degree = 20  # 多项式的最大阶数
n_train, n_test = 100, 100  # 训练和测试数据集大小
true_w = np.zeros(max_degree)  # 分配大量的空间
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])

features = np.random.normal(size=(n_train + n_test, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(max_degree).reshape(1, -1))
for i in range(max_degree):
    poly_features[:, i] /= math.gamma(i + 1)  # gamma(n)=(n-1)!
# labels的维度:(n_train+n_test,)
labels = np.dot(poly_features, true_w)
labels += np.random.normal(scale=0.1, size=labels.shape)

In [3]:
# NumPy ndarray转换为tensor
true_w, features, poly_features, labels = [torch.tensor(x, dtype=
    torch.float32) for x in [true_w, features, poly_features, labels]]

features[:2], poly_features[:2, :], labels[:2]

(tensor([[ 0.3781],
         [-0.6509]]),
 tensor([[ 1.0000e+00,  3.7806e-01,  7.1464e-02,  9.0059e-03,  8.5119e-04,
           6.4360e-05,  4.0553e-06,  2.1902e-07,  1.0350e-08,  4.3479e-10,
           1.6438e-11,  5.6494e-13,  1.7798e-14,  5.1761e-16,  1.3978e-17,
           3.5229e-19,  8.3242e-21,  1.8512e-22,  3.8881e-24,  7.7365e-26],
         [ 1.0000e+00, -6.5087e-01,  2.1181e-01, -4.5954e-02,  7.4775e-03,
          -9.7336e-04,  1.0559e-04, -9.8177e-06,  7.9875e-07, -5.7764e-08,
           3.7597e-09, -2.2246e-10,  1.2066e-11, -6.0410e-13,  2.8085e-14,
          -1.2186e-15,  4.9573e-17, -1.8979e-18,  6.8628e-20, -2.3509e-21]]),
 tensor([5.1653, 3.2700]))

In [4]:
# 训练和测试模型
def evaluate_loss(net, data_iter, loss):  #@save
    """评估给定数据集上模型的损失"""
    metric = d2l.Accumulator(2)  # 损失的总和,样本数量
    for X, y in data_iter:
        out = net(X)
        y = y.reshape(out.shape)
        l = loss(out, y)
        metric.add(l.sum(), l.numel())
    return metric[0] / metric[1]

In [5]:
def train(train_features, test_features, train_labels, test_labels,
          num_epochs=400):
    loss = nn.MSELoss(reduction='none')
    input_shape = train_features.shape[-1]
    # 不设置偏置，因为我们已经在多项式中实现了它
    net = nn.Sequential(nn.Linear(input_shape, 1, bias=False))
    batch_size = min(10, train_labels.shape[0])
    train_iter = d2l.load_array((train_features, train_labels.reshape(-1,1)),
                                batch_size)
    test_iter = d2l.load_array((test_features, test_labels.reshape(-1,1)),
                               batch_size, is_train=False)
    trainer = torch.optim.SGD(net.parameters(), lr=0.01)
    animator = d2l.Animator(xlabel='epoch', ylabel='loss', yscale='log',
                            xlim=[1, num_epochs], ylim=[1e-3, 1e2],
                            legend=['train', 'test'])
    for epoch in range(num_epochs):
        d2l.train_epoch_ch3(net, train_iter, loss, trainer)
        if epoch == 0 or (epoch + 1) % 20 == 0:
            animator.add(epoch + 1, (evaluate_loss(net, train_iter, loss),
                                     evaluate_loss(net, test_iter, loss)))
    print('weight:', net[0].weight.data.numpy())