In [1]:
# 不带参数的层
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [4]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.Linear(8,128), CenteredLayer())

In [7]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(3.2596e-09, grad_fn=<MeanBackward0>)

In [8]:
# 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.7311,  0.1155, -0.6554],
        [-0.3646, -0.5694,  0.9163],
        [ 0.7409, -0.5855, -0.6427],
        [-0.4115,  1.3330,  0.9422],
        [ 1.3239, -1.2489,  0.3772]], requires_grad=True)

In [10]:
linear(torch.rand(2, 5))

tensor([[2.6475, 0.0000, 0.8106],
        [2.0347, 0.4490, 0.5860]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.9059],
        [0.3849]])