In [2]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [3]:
# 查询GPU数量
torch.cuda.device_count()

1

In [4]:
# 两个函数允许我们在不存在所需所有GPU的情况下运行代码，以避免报错
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')


def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]"""
    devices = [torch.device(f'cuda:{i}')
               for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]


try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [5]:
# 张量在cpu上创建的
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [7]:
# 存储在gpu上
X = torch.ones(2, 3, device=try_gpu())
print(X)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [13]:
Y = torch.rand(2, 3, device=try_gpu(0))
print(Y)

tensor([[0.8455, 0.5702, 0.0653],
        [0.7537, 0.0892, 0.5836]], device='cuda:0')


In [14]:
Z = X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [15]:
Y + Z

tensor([[1.8455, 1.5702, 1.0653],
        [1.7537, 1.0892, 1.5836]], device='cuda:0')

In [16]:
# 将代码放在gpu上
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

In [17]:
net(X)

tensor([[-0.2552],
        [-0.2552]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [18]:
net[0].weight.data.device

device(type='cuda', index=0)